runtime: python39
service: demo-cicd-django
entrypoint: gunicorn -b :$PORT app_engine.wsgi:application

instance_class: F1

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: app_engine.settings
