runtime: python39  # Specifies the runtime environment. In this case, Python 3.9
entrypoint: gunicorn -b :$PORT main:app  # Defines the entry point for the application. Adjust according to your app server and application.

# [Optional] Instance Class Configuration
instance_class: F1  # Defines the instance class (compute resources). F1 is the smallest available instance class.

# [Optional] Resource Files
handlers:
- url: /static  # URL path for static files
  static_dir: static/  # Directory within your project that contains static files.

- url: /.*  # Catch-all handler to serve a web application.
  script: auto  # Automatically route requests to your applicatio