name: Deploy to GCP App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yml --quiet
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
